# Generated by Django 6.0.5 on 2026-05-13 18:56

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "milestones",
                "ordering": ["deadline"],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("short_title", models.CharField(blank=True, max_length=100)),
                ("abstract", models.TextField(blank=True)),
                ("problem_statement", models.TextField(blank=True)),
                ("research_gap", models.TextField(blank=True)),
                ("objective", models.TextField(blank=True)),
                ("methodology", models.TextField(blank=True)),
                ("expected_contribution", models.TextField(blank=True)),
                ("funding_source", models.CharField(blank=True, max_length=255)),
                (
                    "ethics_approval_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("sdg_goals", models.JSONField(blank=True, default=list)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("ml", "Machine Learning"),
                            ("nlp", "NLP"),
                            ("cv", "Computer Vision"),
                            ("healthcare", "Healthcare AI"),
                            ("security", "Cybersecurity"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    django_fsm.FSMField(
                        default="idea_proposed", max_length=50, protected=True
                    ),
                ),
                (
                    "literature_review_progress",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("dataset_progress", models.PositiveSmallIntegerField(default=0)),
                ("experiment_progress", models.PositiveSmallIntegerField(default=0)),
                ("writing_progress", models.PositiveSmallIntegerField(default=0)),
                ("revision_progress", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "papers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("affiliation", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("orcid", models.CharField(blank=True, max_length=50)),
                ("google_scholar_link", models.URLField(blank=True)),
                ("author_order", models.PositiveSmallIntegerField(default=1)),
                (
                    "contribution_percentage",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("is_corresponding", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "paper_authors",
                "ordering": ["author_order"],
            },
        ),
        migrations.CreateModel(
            name="PaperMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("issn", models.CharField(blank=True, max_length=20)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("conference_name", models.CharField(blank=True, max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("journal_quartile", models.CharField(blank=True, max_length=5)),
                (
                    "impact_factor",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("indexing", models.JSONField(blank=True, default=list)),
                (
                    "apc_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "acceptance_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("submission_deadline", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "paper_metadata",
            },
        ),
    ]
