# Generated by Django 6.0.5 on 2026-05-15 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("papers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteratureEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                (
                    "authors",
                    models.TextField(
                        blank=True, help_text="Comma-separated author names"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("journal", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("method", models.TextField(blank=True)),
                ("dataset", models.TextField(blank=True)),
                ("limitations", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="literature_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="literature_entries",
                        to="papers.paper",
                    ),
                ),
            ],
            options={
                "db_table": "literature_entries",
                "ordering": ["-year", "title"],
            },
        ),
    ]
