# Generated by Django 6.0.5 on 2026-05-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_url", models.URLField(max_length=1000)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("manuscript", "Manuscript"),
                            ("dataset", "Dataset"),
                            ("source_code", "Source Code"),
                            ("figures", "Figures"),
                            ("ethics", "Ethics Documents"),
                            ("reviewer_response", "Reviewer Response"),
                            ("supplementary", "Supplementary Files"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("is_locked", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
