# Generated by Django 6.0.5 on 2026-05-13 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                        ],
                        default="journal",
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("quartile", models.CharField(blank=True, max_length=5)),
                (
                    "impact_factor",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("submission_link", models.URLField(blank=True)),
                (
                    "review_duration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "acceptance_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("formatting_template_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "venues",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("submission_id", models.CharField(blank=True, max_length=100)),
                ("manuscript_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("revision_requested", "Revision Requested"),
                            ("resubmitted", "Resubmitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=25,
                    ),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("review_deadline", models.DateField(blank=True, null=True)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="papers.paper",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="submissions.venue",
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
